
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example.lparser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHILE = 13;
  public static final int LBRACE = 6;
  public static final int INTEGER = 9;
  public static final int NUMBER = 14;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int IF = 11;
  public static final int ID = 15;
  public static final int ELSE = 12;
  public static final int ASSIGN = 8;
  public static final int error = 1;
  public static final int RPAREN = 5;
  public static final int RETURN = 10;
  public static final int LPAREN = 4;
  public static final int RBRACE = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "ASSIGN",
  "INTEGER",
  "RETURN",
  "IF",
  "ELSE",
  "WHILE",
  "NUMBER",
  "ID"
  };
}

